#!/bin/sh

if [ "$#" -ne 3 ]; then
    echo "Convert csv to sqlite."
    echo "Usage: sqldec <file.csv> <plain-db> <table-name>"
    exit 1
fi

CSV_FILE=$1
PLAIN_DB=$2
TABLE_NAME=$3

if test ! -f "$CSV_FILE"; then
    echo "File $CSV_FILE does not exist"
    exit 1
fi

if test -f "$PLAIN_DB"; then
    echo "File $PLAIN_DB already exists"
    exit 1
fi


sqlcipher ${PLAIN_DB} <<EOF
.mode csv ;
.import '${CSV_FILE}' '${TABLE_NAME}'
EOF